### ISSUE TITLE
appraisal rake test fails -- `require': cannot load such file -- test/unit/testcase (LoadError)

### ISSUE THREAD

**Issue by Fedcomp** [stefankroes/ancestry#249]
Gemfile missing
```
gem 'test-unit'
```
Should i provide pull request?

```
$ bundle
Resolving dependencies...
Using rake 10.1.0
Using i18n 0.6.9
Using minitest 4.7.5
Using multi_json 1.8.2
Using atomic 1.1.14
Using thread_safe 0.1.3
Using tzinfo 0.3.38
Using activesupport 4.0.2
Using builder 3.1.4
Using activemodel 4.0.2
Using activerecord-deprecated_finders 1.0.3
Using arel 4.0.1
Using activerecord 4.0.2
Using ancestry 2.1.0 from source at .
Using bundler 1.9.9
Using thor 0.18.1
Using appraisal 1.0.0.beta1
Using mime-types 2.0
Using rest-client 1.6.7
Using docile 1.1.1
Using simplecov-html 0.8.0
Using simplecov 0.8.2
Using tins 0.13.1
Using term-ansicolor 1.2.2
Using coveralls 0.7.0
Using json 1.8.1
Using pg 0.17.1
Using rdoc 4.0.1
Bundle complete! 6 Gemfile dependencies, 28 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

$ appraisal rake test
>> BUNDLE_GEMFILE=/home/user/github/ancestry/gemfiles/sqlite3_ar_30.gemfile bundle exec rake test
/home/user/.rvm/rubies/ruby-2.2.1/bin/ruby -I"lib:lib:test"  "/home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/rake_test_loader.rb" "test/**/*_test.rb" 
/home/user/.rvm/gems/ruby-2.2.1/gems/activesupport-3.0.20/lib/active_support/test_case.rb:1:in `require': cannot load such file -- test/unit/testcase (LoadError)
        from /home/user/.rvm/gems/ruby-2.2.1/gems/activesupport-3.0.20/lib/active_support/test_case.rb:1:in `<top (required)>'
        from /home/user/github/ancestry/test/environment.rb:5:in `require'
        from /home/user/github/ancestry/test/environment.rb:5:in `<top (required)>'
        from /home/user/github/ancestry/test/concerns/arrangement_test.rb:1:in `require_relative'
        from /home/user/github/ancestry/test/concerns/arrangement_test.rb:1:in `<top (required)>'
        from /home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/rake_test_loader.rb:10:in `require'
        from /home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/rake_test_loader.rb:10:in `block (2 levels) in <main>'
        from /home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/rake_test_loader.rb:9:in `each'
        from /home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/rake_test_loader.rb:9:in `block in <main>'
        from /home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/rake_test_loader.rb:4:in `select'
        from /home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
Command failed with status (1): [ruby -I"lib:lib:test"  "/home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/rake_test_loader.rb" "test/**/*_test.rb" ]
/home/user/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/home/user/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => test
(See full trace by running task with --trace)
```

**Comment by Fedcomp** [comment]
Now i when i run tests i cant test against active record 4.0+, test suite just not starting. What do i miss?

**Comment by kbrock** [comment]
I have the same issue. trying to track down

**Comment by Fedcomp** [comment]
for AR 4+ i had to require 'minitest/autorun', after it, test suite worked, but i guess it's wrong fix.
Also ancestry sorting with block test is failing (ScopeTest sort with block), my guess is that it never been green.

**Comment by kbrock** [comment]
thanks. Yea. I just started digging into this over the past few days.

I want to go over to mini-test

**Comment by kbrock** [comment]
please let me know if you have any issues or questions around this
