### ISSUE TITLE
Issues with ActiveRecord / Rails 5.1

### ISSUE THREAD

**Issue by jwigal** [stefankroes/ancestry#366]
I'm seeing some issues with ancestry callbacks not firing properly in ActiveRecord 5.1. Been digging around and haven't been able to see why things aren't working correctly. 

Here's a short test that is failing in my app. Department is a model that includes ancestry. Both `level_2` and `level_3` are not properly setting their ancestry attribute.

    test "ancestry includes multiple levels" do 
      level_1 = create(:department)
      level_2 = create(:department, parent: level_1)
      level_3 = create(:department, parent: level_2)
      assert level_3.ancestors.reload.include?(level_1)
    end

Ran the test suite and am seeing multiple failing tests when I lock the version of ActiveRecord to 5.1:

    $ rake test
    /Users/jeff/.rvm/rubies/ruby-2.3.3/bin/ruby -I"lib:test" -I"/Users/jeff/.rvm/gems/ruby-2.3.3/gems/rake-10.5.0/lib" "/Users/jeff/.rvm/gems/ruby-2.3.3/gems/rake-10.5.0/lib/rake/rake_test_loader.rb" "test/**/*_test.rb" 

    Loaded Ancestry test suite environment:
      Ruby: 2.3.3
      ActiveRecord: 5.1.4
      Database: SQLite

    Run options: --seed 36596

    # Running:

    F....FFFF....F.FFF.......F....FF....F.E..F.FF.F..E...F....F.........

    Finished in 3.670442s, 18.5264 runs/s, 307.0475 assertions/s.

      1) Failure:
    BuildAncestryTest#test_build_ancestry_from_parent_ids [/Users/jeff/code/ancestry/test/concerns/build_ancestry_test.rb:33]:
    Expected: 5
      Actual: 0

      2) Failure:
    DepthConstraintsTest#test_ancestors_with_depth_constraints [/Users/jeff/code/ancestry/test/concerns/depth_constraints_test.rb:34]:
    --- expected
    +++ actual
    @@ -1 +1 @@
    -[#<AncestryTestDatabase::TestAncestorsWithDepthConstraintsTestNode id: 1, ancestry: nil, ancestry_depth: 0>, #<AncestryTestDatabase::TestAncestorsWithDepthConstraintsTestNode id: 2, ancestry: "1", ancestry_depth: 1>, #<AncestryTestDatabase::TestAncestorsWithDepthConstraintsTestNode id: 3, ancestry: "2", ancestry_depth: 1>]
    +#<ActiveRecord::Relation []>

      3) Failure:
    DepthConstraintsTest#test_descendants_with_depth_constraints [/Users/jeff/code/ancestry/test/concerns/depth_constraints_test.rb:7]:
    Expected: 20
      Actual: 4

      4) Failure:
    DepthConstraintsTest#test_path_with_depth_constraints [/Users/jeff/code/ancestry/test/concerns/depth_constraints_test.rb:51]:
    --- expected
    +++ actual
    @@ -1 +1 @@
    -[#<AncestryTestDatabase::TestPathWithDepthConstraintsTestNode id: 1, ancestry: nil, ancestry_depth: 0>, #<AncestryTestDatabase::TestPathWithDepthConstraintsTestNode id: 2, ancestry: "1", ancestry_depth: 1>, #<AncestryTestDatabase::TestPathWithDepthConstraintsTestNode id: 3, ancestry: "2", ancestry_depth: 1>]
    +#<ActiveRecord::Relation []>

      5) Failure:
    DepthConstraintsTest#test_subtree_with_depth_constraints [/Users/jeff/code/ancestry/test/concerns/depth_constraints_test.rb:17]:
    Expected: 21
      Actual: 5

      6) Failure:
    ArrangementTest#test_subtree_arrange_root_node [/Users/jeff/code/ancestry/test/concerns/arrangement_test.rb:54]:
    Expected: 2
      Actual: 0

      7) Failure:
    ArrangementTest#test_path_arrange_leaf_node [/Users/jeff/code/ancestry/test/concerns/arrangement_test.rb:105]:
    Expected: 1
      Actual: 2

      8) Failure:
    ArrangementTest#test_descendants_arrange_root_node [/Users/jeff/code/ancestry/test/concerns/arrangement_test.rb:72]:
    Expected: 2
      Actual: 0

      9) Failure:
    ArrangementTest#test_subtree_arrange_middle_node [/Users/jeff/code/ancestry/test/concerns/arrangement_test.rb:60]:
    Expected: 1
      Actual: 3

     10) Failure:
    ArrangementTest#test_descendants_arrange_middle_node [/Users/jeff/code/ancestry/test/concerns/arrangement_test.rb:78]:
    Expected: 2
      Actual: 0

     11) Failure:
    ValidationsTest#test_validate_ancestry_exclude_self [/Users/jeff/code/ancestry/test/concerns/validations_test.rb:22]:
    ActiveRecord::RecordInvalid expected but nothing was raised.

     12) Failure:
    StiSupportTest#test_sti_support [/Users/jeff/code/ancestry/test/concerns/sti_support_test.rb:21]:
    Expected: [2, 3, 4, 5]
      Actual: [2]

     13) Failure:
    TreeNavigationTest#test_tree_navigation [/Users/jeff/code/ancestry/test/concerns/tree_navigration_test.rb:74]:
    Expected: [1, 2]
      Actual: [2]

     14) Error:
    IntegrityCheckingAndRestaurationTest#test_integrity_checking:
    Ancestry::AncestryIntegrityException: Conflicting parent id found in node 3: nil for node 2 while expecting 1
        /Users/jeff/code/ancestry/lib/ancestry/class_methods.rb:120:in `block (3 levels) in check_ancestry_integrity!'
        /Users/jeff/code/ancestry/lib/ancestry/class_methods.rb:117:in `each'
        /Users/jeff/code/ancestry/lib/ancestry/class_methods.rb:117:in `block (2 levels) in check_ancestry_integrity!'
        /Users/jeff/.rvm/gems/ruby-2.3.3/gems/activerecord-5.1.4/lib/active_record/relation/batches.rb:63:in `block (2 levels) in find_each'
        /Users/jeff/.rvm/gems/ruby-2.3.3/gems/activerecord-5.1.4/lib/active_record/relation/batches.rb:63:in `each'
        /Users/jeff/.rvm/gems/ruby-2.3.3/gems/activerecord-5.1.4/lib/active_record/relation/batches.rb:63:in `block in find_each'
        /Users/jeff/.rvm/gems/ruby-2.3.3/gems/activerecord-5.1.4/lib/active_record/relation/batches.rb:129:in `block in find_in_batches'
        /Users/jeff/.rvm/gems/ruby-2.3.3/gems/activerecord-5.1.4/lib/active_record/relation/batches.rb:230:in `block in in_batches'
        /Users/jeff/.rvm/gems/ruby-2.3.3/gems/activerecord-5.1.4/lib/active_record/relation/batches.rb:214:in `loop'
        /Users/jeff/.rvm/gems/ruby-2.3.3/gems/activerecord-5.1.4/lib/active_record/relation/batches.rb:214:in `in_batches'
        /Users/jeff/.rvm/gems/ruby-2.3.3/gems/activerecord-5.1.4/lib/active_record/relation/batches.rb:128:in `find_in_batches'
        /Users/jeff/.rvm/gems/ruby-2.3.3/gems/activerecord-5.1.4/lib/active_record/relation/batches.rb:62:in `find_each'
        /Users/jeff/code/ancestry/lib/ancestry/class_methods.rb:104:in `block in check_ancestry_integrity!'
        /Users/jeff/code/ancestry/lib/ancestry/class_methods.rb:206:in `unscoped_where'
        /Users/jeff/code/ancestry/lib/ancestry/class_methods.rb:102:in `check_ancestry_integrity!'
        /Users/jeff/code/ancestry/test/concerns/integrity_checking_and_restoration_test.rb:8:in `block (2 levels) in test_integrity_checking'
        /Users/jeff/.rvm/gems/ruby-2.3.3/gems/activesupport-5.1.4/lib/active_support/testing/assertions.rb:30:in `assert_nothing_raised'
        /Users/jeff/code/ancestry/test/concerns/integrity_checking_and_restoration_test.rb:7:in `block in test_integrity_checking'
        /Users/jeff/code/ancestry/test/environment.rb:102:in `with_model'
        /Users/jeff/code/ancestry/test/concerns/integrity_checking_and_restoration_test.rb:5:in `test_integrity_checking'

     15) Failure:
    HasAncestryTreeTest#test_set_parent_with_non_default_ancestry_column [/Users/jeff/code/ancestry/test/concerns/has_ancestry_test.rb:63]:
    "root1.descendants.size" didn't change by 0.
    Expected: 3
      Actual: 0

     16) Failure:
    HasAncestryTreeTest#test_set_parent_id [/Users/jeff/code/ancestry/test/concerns/has_ancestry_test.rb:75]:
    "root1.descendants.size" didn't change by 0.
    Expected: 3
      Actual: 0

     17) Failure:
    HasAncestryTreeTest#test_set_parent_id_with_non_default_ancestry_column [/Users/jeff/code/ancestry/test/concerns/has_ancestry_test.rb:87]:
    "root1.descendants.size" didn't change by 0.
    Expected: 3
      Actual: 0

     18) Failure:
    HasAncestryTreeTest#test_descendants_move_with_node [/Users/jeff/code/ancestry/test/concerns/has_ancestry_test.rb:37]:
    "root1.descendants.size" didn't change by 0.
    Expected: 3
      Actual: 0

     19) Error:
    DepthCachingTest#test_depth_caching_after_subtree_movement:
    NoMethodError: undefined method `update_attributes' for nil:NilClass
        /Users/jeff/code/ancestry/test/concerns/depth_caching_test.rb:21:in `block in test_depth_caching_after_subtree_movement'
        /Users/jeff/code/ancestry/test/environment.rb:102:in `with_model'
        /Users/jeff/code/ancestry/test/concerns/depth_caching_test.rb:19:in `test_depth_caching_after_subtree_movement'

     20) Failure:
    DepthCachingTest#test_depth_caching [/Users/jeff/code/ancestry/test/concerns/depth_caching_test.rb:11]:
    Expected: 2
      Actual: 1

     21) Failure:
    OphanStrategiesTest#test_orphan_adopt_strategy [/Users/jeff/code/ancestry/test/concerns/orphan_strategies_test.rb:83]:
    orphan's not parentified.
    --- expected
    +++ actual
    @@ -1 +1 @@
    -nil
    +#<AncestryTestDatabase::TestOrphanAdoptStrategyTestNode id: 1, ancestry: nil>

    68 runs, 1127 assertions, 19 failures, 2 errors, 0 skips

**Comment by jwigal** [comment]
Disregard, I'm working with a fork rather than the main branch. Sorry!
